ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POST_LIKED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ANSWER_LIKED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIROBA_POST_ANSWERED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIROBA_POST_LIKED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIROBA_ANSWER_LIKED';

ALTER TABLE "Notification"
ADD COLUMN "hirobaPostId" TEXT,
ADD COLUMN "hirobaAnswerId" TEXT;

ALTER TABLE "Notification"
ADD CONSTRAINT "Notification_hirobaPostId_fkey"
FOREIGN KEY ("hirobaPostId") REFERENCES "HirobaPost"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Notification"
ADD CONSTRAINT "Notification_hirobaAnswerId_fkey"
FOREIGN KEY ("hirobaAnswerId") REFERENCES "HirobaAnswer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
