export const HIROBA_POST_IMAGE_MAX_MB = 4.5
export const HIROBA_POST_IMAGE_MAX_BYTES = HIROBA_POST_IMAGE_MAX_MB * 1024 * 1024
export const HIROBA_POST_IMAGE_TOO_LARGE_MESSAGE = `ファイルサイズが大きすぎます（${HIROBA_POST_IMAGE_MAX_MB}MB以下にしてください）`
export const HIROBA_POST_IMAGE_MAX_SIZE = 1600
